"use client";
import "./globals.css";
import { Ubuntu } from "next/font/google";
import React from "react";
import UsetateNavbar from "./component/UsetateNavbar";
import UsetateFooter from "./component/UsetateFooter";
import { SessionProvider } from "next-auth/react";

const ubuntu = Ubuntu({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-ubuntu",
  fallback: ["sans-serif"],
  
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>BILBUL</title>
        <meta
          name="Apps For Education"
          content="Generated by create next app"
        />
        <link rel="icon" href="/Bilcon.png" />
      </head>
      <body
        className={`${ubuntu.className} dark:bg-[#111827] text-white h-screen w-screen`}
      >
        <SessionProvider>
          <UsetateNavbar />
          {children}
          <UsetateFooter />
        </SessionProvider>
      </body>
    </html>
  );
}
