"use client";
import "./globals.css";
import { Roboto } from "next/font/google";
import React from "react";
import UsetateNavbar from "./component/UsetateNavbar";
import UsetateFooter from "./component/UsetateFooter";
import { SessionProvider } from "next-auth/react";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>BILBUL</title>
        <meta
          name="Apps For Education"
          content="Generated by create next app"
        />
        <link rel="icon" href="/Bilcon.png" />
      </head>
      <body
        className={`${roboto.className} dark:bg-black text-white h-screen w-screen`}
      >
        <SessionProvider>
          <UsetateNavbar />
          {children}
          <UsetateFooter />
        </SessionProvider>
      </body>
    </html>
  );
}
