import "./globals.css";
import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import React from "react";
import UsetateNavbar from "./component/UsetateNavbar";
import UsetateFooter from "./component/UsetateFooter";
import { AppWrapper } from "./context/AppWrapper";

const ubuntu = Ubuntu({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-ubuntu",
  fallback: ["sans-serif"],
});

export const metadata: Metadata = {
  title: "BILBUL",
  description: "Application For Education",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <title>BILBUL</title>
        <meta
          name="Apps For Education"
          content="Generated by create next app"
        />
        <link rel="icon" href="/Bilcon.png" />
      </head>
      <body
        className={`${ubuntu.className} dark:bg-[#111827] text-white h-screen w-screen`}
      >
        <AppWrapper>
          <UsetateNavbar />
          {children}
          <UsetateFooter />
        </AppWrapper>
      </body>
    </html>
  );
}
